# Generated by Django 3.1.2 on 2020-11-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201101_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
